@startuml AttributionSalle
hide footbox
skinparam sequenceMessageAlign center

actor MembreDuPersonnel
participant système

Activate système

== Connexion ==

MembreDuPersonnel -> système : demande connexion
MembreDuPersonnel <<-- système : accepte la demande
MembreDuPersonnel <- système : demande login et mot de passe
MembreDuPersonnel -->> système : entre login et mot de passe

loop login ou mot de passe incorrect
    MembreDuPersonnel <- système : redemande login et mot de passe
    MembreDuPersonnel -->> système : rentre login et mot de passe
end

== Election d'une séance ==

MembreDuPersonnel -> système : demande à consulter l'ensemble des séances (film, horaire)
MembreDuPersonnel <<-- système : accepte la demande

alt Séance sans salle attribuée
    MembreDuPersonnel -->> système : Sélectionne une séance sans salle attribuée
end 

== Election d'une salle ==

MembreDuPersonnel <- système : Fournit les salles disponibles pour le créneau horaire spécifié

loop Pas de salle disponible \n OU \n Pas de salle correcte (nb place, dolby...)
    MembreDuPersonnel <- système : demande adresse mail

    MembreDuPersonnel <<[#red]-- système : <font color=red>Arrête l'attribution d'un salle</font>
end

    MembreDuPersonnel <<[#green]-- système : <font color=green>Confirme l'attribution d'un salle</font>
