@startuml
left to right direction

[*] -> enAttente
enAttente->[*] : éteindre

enAttente --> FilmChoisi : choisirFilm [FilmTrouvé] /

enAttente <- FilmChoisi : choisirFilm [FilmNonTrouvé] /
FilmChoisi --> HoraireChoisi : choisirHoraire [FilmTrouvé] /

FilmChoisi <- HoraireChoisi : choisirHoraire [HoraireNonDisponibles] /
HoraireChoisi --> PlacesChoisies : choisirHoraire [HoraireDisponibles] /

HoraireChoisi <- PlacesChoisies : choisirPlaces [placesNonDisponibles] /
PlacesChoisies --> TarifsChoisis : choisirPlaces [placesDisponibles] /

TarifsChoisis --> Transaction : choisirTarifs [] /

Transaction <- Transaction : paiement [Refusé] /
Transaction --> enAttente : paiement [Accepté] / EnvoyerMail


@enduml